### PR TITLE
Adding link to latest spec to main menu

### PR DESCRIPTION
**Pull request by gunnarmorling**
The ribbon didn't play together with the menu pulled to the right side. I've put the link to the menu itself, giving it some sort of emphasize.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Any thoughts, @gsmet?

**Comment by gsmet** [comment]
Not very convinced by the halo around the link. Maybe just a simple "text-shadow: 1px 1px 1px #ccc" would be sufficient?

FYI I have planned to spend some time on the website once we have the logo.

**Comment by gunnarmorling** [comment]
Sure, change it as you like.

**Comment by gsmet** [comment]
Merged a slightly different version validated with Gunnar.

**Pull request closed without merging**
