### PR TITLE
Upgrade website to latest Awestruct and ideally new skin

### PR DESCRIPTION
**Pull request by xcoulon**
Here is a proposal with 2 commits:
- first commit is a simple migration to awestruct 0.5.6 (updating the gem files)
- second commit is a new theme proposal based on the [PatternFly template](http://patternfly.org). This commit includes new layouts, stylesheets and some page changes (eg: moving /index.html.haml to /index.adoc and moving some .md to .adoc). Stylesheet can be updated if colors should be different from the default Patternfly template, of course.

Please let me know what you think about it.

### CODE REVIEW

**Comment by hferentschik** [comment]
nice, definitely a step into the right direction. The black banner on the home page is imo a bit too big and I am not so sure about the plain "Bean Validation". Is this "box" just for a title or can one also add some short abstract into this box. A logo would be awesome as well, but there is none of course (at least not officially).

One thing we also need to address is the separation between BV 1.0, BV 1.1 and the coming BV 2.0. This is not necessarily in the scope of this issue, but I am wondering how one would do it with this skin? Could the top left "Bean Validation" link be a dropdown of sorts where one could select the BV version? Default would currently be 1.1, but then 2.0.

**Comment by xcoulon** [comment]
hello @hferentschik !
thanks for you feedback ;-)

Yes, the front box may need more work or could be removed. And yes, a logo and a tagline would be nice additions. As I wrote earlier, I took used the patternfly.org layout and took inspiration on the patternfly.org website. But again, this is just some draft proposal.

As far as BV 1.0/1.1/2.0 separation are concerned, we could use dropdown menus, indeed. The patternfly.org website uses them to access layouts, patterns, widgets, etc.

**Comment by emmanuelbernard** [comment]
Thanks Xavier!
Here are the issues I've found:

* indeed the Bean Validation banner is quite big, if we could up some tagline, that might work? Or a smaller one
* /news/ has a few issues
    * latest post are copied twice on the right: it should be none. In fact it should only veisible on the homepage and not on the other pages
    * title is written twice (we could fix the actual posts - not a lot of them - if that helps Asciidoctor support
* i find fonts a bit small
* tables like /1.1/certified/ look weird as the header columns are not very distinguished
* we lost the RI link in the header
* TODO: check that the atom feed is correctly/similarly generated
* Asciidoc pages with `:toc:` don't show a very nice ToC, needs CSS'ing
* `TIP` and `NOTE` are not rendered very well in Asciidoc
* the first page is slow, is that expected, where is the late building option set?

Also there is a failure when building the site but the site ends up being built.

```
rake preview
bundle exec awestruct -d
Using profile: development
Generating site: http://localhost:4242
Excecuting pipeline...
undefined method `init' for Guard:Module
/Users/emmanuel/Code/beanvalidation/beanvalidation.org/.bundle/ruby/2.1.0/gems/awestruct-0.5.6/lib/awestruct/cli/auto.rb:23:in `run'
/Users/emmanuel/Code/beanvalidation/beanvalidation.org/.bundle/ruby/2.1.0/gems/awestruct-0.5.6/lib/awestruct/cli/invoker.rb:144:in `invoke_auto'
/Users/emmanuel/Code/beanvalidation/beanvalidation.org/.bundle/ruby/2.1.0/gems/awestruct-0.5.6/lib/awestruct/cli/invoker.rb:53:in `invoke!'
/Users/emmanuel/Code/beanvalidation/beanvalidation.org/.bundle/ruby/2.1.0/gems/awestruct-0.5.6/bin/awestruct:9:in `<top (required)>'
/Users/emmanuel/Code/beanvalidation/beanvalidation.org/.bundle/ruby/2.1.0/bin/awestruct:23:in `load'
/Users/emmanuel/Code/beanvalidation/beanvalidation.org/.bundle/ruby/2.1.0/bin/awestruct:23:in `<main>'
***************************************************************************
Starting preview server at http://localhost:4242 (Press Ctrl-C to shutdown)
***************************************************************************

[2016-02-01 13:48:43] INFO  WEBrick 1.3.1
[2016-02-01 13:48:43] INFO  ruby 2.1.4 (2014-10-27) [x86_64-darwin13.0]
[2016-02-01 13:48:43] INFO  WEBrick::HTTPServer#start: pid=82896 port=4242
```

**Comment by xcoulon** [comment]
@emmanuelbernard 
thanks for your feedback. I'll update the PR to fix all the problems you reported. I also noticed the errors at startup but I did not dig further into them since the website builds (I think the issues are related to livereload support)
Also, I suspect some CSS compilation that would explain why the first page loading is so slow (and yes, it's a bit painful).

**Comment by emmanuelbernard** [comment]
Thanks @xcoulon :)

**Comment by gunnarmorling** [comment]
@xcoulon, nothing much to add to what the others said. But great stuff, awesome that you took over this one!

**Comment by gunnarmorling** [comment]
Regarding a tagline, didn't we use "constrain once, validate everywhere" at some point?

**Comment by emmanuelbernard** [comment]
yep

**Comment by xcoulon** [comment]
@emmanuelbernard I just opened https://github.com/awestruct/awestruct/issues/508 with regards to the error message that appears when running the website.

**Comment by xcoulon** [comment]
Last update in this PR includes the use of Sassc/Libsass to compile the patternfly stylesheets, and it's much faster than before, so there's no lag when requesting the first page after a clean restart of awestruct. Also, using the latest version of Awestruct, the guard/livereload support works again and there's no error at startup.

**Comment by DavideD** [comment]
Hi @xcoulon, are you still working on this?
it semms that the website works nicely now but there are still CSS issues to fix.

Tomorrow I could take it from here and fix them,
if it's ok for you. Let me know.

Cheers

**Comment by xcoulon** [comment]
Hello @DavideD 

Yes, I still have a bunch of fixes to push in this pull request. Let me do it this morning, then you can apply yours on top of mine. If you submit a PR on my branch, I can include your commits in here. 

ok for you ?

**Comment by DavideD** [comment]
I haven't started to work on it yet, I will wait for you to finish the
fixes. Thanks

**Comment by xcoulon** [comment]
@DavideD @emmanuelbernard I just pushed another commit on this PR with the following changes and fixes :

- Using a free background pattern (from http://subtlepatterns.org)
      and setting the top navbar background color to transparent instead
      of dark, so it's closer to the actual site and looks less like an app
- Fixing the /news/ layout
- Increasing font size (using patternfly sass variables)
- Restoring the missing "RI" menu

The tables (eg: /1.1/certified) still need some fixes in the CSS. We need to check if patternfly brings its own classes or if there were removed when I updated the stylesheets.

I kept the navbar on the right side on individual blog posts, because I believe that it will engage readers to browse other articles instead of having to click on the "Back" button. 

That being said, a breadcrumb could be a nice addition in the site.

Also, as I suggested before, some dropdown menus to display the content for the different versions of the spec could be a solution.

**Comment by xcoulon** [comment]
Also, as a remark: building the webiste with Awestruct requires Ruby 2.0 or higher. There is no such enforcement in Gemfile for now, but it could be nice to make sure that all developers use the same version of Ruby.

**Comment by emmanuelbernard** [comment]
Thanks @xcoulon !
Are you sure it's http://subtlepatterns.org/ The website looks like a parked website of sort.

**Comment by xcoulon** [comment]
@emmanuelbernard right, the home page is wrong. I should have been http://subtlepatterns.com/ instead. I'll fix the commit message, too

**Comment by xcoulon** [comment]
@emmanuelbernard BTW, the use of a background pattern on the home page is experimental, so feedback is welcome. The subtlepatterns.com site has a lot of free light/dark patterns, I just picked one ;-)

There's also an interesting pattern generator based on the words you input: https://github.com/jasonlong/geo_pattern or you can try its online version http://btmills.github.io/geopattern/geopattern.html ;-)

**Comment by xcoulon** [comment]
Pushed another commit that fixes the table styling on /1.1/certified, while converting the file from .md to .adoc and inheriting the patternfly's CSS rules.

I think the site is also missing some .js to convert the top navbar into a drop-down menu when the page is too narrow.

**Comment by emmanuelbernard** [comment]
That looks awesome.

## Blocking that needs fixing before going live
- [ ] proposals e.g. </proposals/BVAL-208/>, roadmap </roadmap/> and I imagine all pages using the default layout (except the home page) have the title written twice.
- [ ] verify that the atom feed and identical or compliant between the old and new site

## Non blocking for initial push
- [ ] I would prefer if h1 -> h6 elements had a different color (not black) to make it easier to see sections
- [ ] the top banner is not responsive on mobile

### Blocking Asciidoctor support
- [ ] Comments  
  In `md` pages, one can add `comments: true` to enable comments. Asciidoctor pages don't seem to support it. I tried `:comments: true` and `:awestruct-comments: true`. An attribute would be best but we could work around it by having different layouts.

### Non blocking Asciidoctor support
- [ ] Add support for code highlighting
- [ ] `NOTE` and `TIPS` are not skinned at all. Best would be with actual pictograms (like plain Asciidoctor does).

@DavideD can you take the first issues in order?

**Comment by emmanuelbernard** [comment]
Here is my test file for Asciidoctor BTW

`/test.adoc`

```
= This is a test
Emmanuel Bernard
:awestruct-layout: default
:toc:
:numbered:
:awestruct-comments: true

https://hibernate.onjira.com/browse/BVAL-327[JIRA]

== Problem

Getters are the vehicle for properties which are handled in Bean Validation 1.0.
Should we also consider getter calls as regular methods. There are pros and cons for 
both approaches. Let's list them

NOTE: test

And we resume

== Pros

A getter is a method: for the sake of consistency and least surprise, we should
consider getters when methods are validated.

TIP: and tips

Action methods starting with `get` would be considered getters and excluded from
method validation.

Components subject to method validation (CDI components) are typically not the ones
hosting properties - though see below in cons.

== Cons

Applications with existing constrained properties might fail due to validation happening
at previously unexpected times (ie when getters are called).

Most `getProperty` / `isProperty` methods are getters 80%/20% rule.

While the problem might not be acute for CDI and its currently limited interception
capabilities, technologies like AspectJ will intercept and validate getters in
a much broader area.

Also, there are some thinking about making JPA entities actual CDI beans in which
case all getter calls could be intercepted. This is coming from the rich entity camp.
While not considered for EE 7, that might very well come in the future.

== Customization mechanisms

Because the choice is not clear, the consensus is that some customization 
mechanism should be available, either:

* as proprietary extensions
* as spec defined

Due to the usefulness and the usage impact with other specification integrations
I think we should standardize it in the specification.

=== Assuming getters are not considered methods to be validated by default

We could offer the following options:

* a global flag to enable getter validation +
  I fail to see the use case ATM, idea?
* a per method or per class flag `@ValidateOnCall(GETTER)` +
  that would require to define class inheritance rules on this annotation
  as well as method inheritance

=== Assuming getters are considered methods to be validated by default

We could offer the following options:

* a global flag to disable getter validation  
  we would use a global flag to disable JPA entity getter validations for example
* a per method or per class flag `@ValidateOnCall(GETTER)`  
  that would require to define class inheritance rules on this annotation
  as well as method inheritance

=== Assuming method validation has to be activated

We could envision to force all components expecting method validation to be
annotated either at the method or class level.

[source,java]
----
@ValidateOnCall({GETTERS, METHODS})
public class AddressService {
    public void addAddress(
        @NotNull @Valid User user, @Valid @NotNull Address address) {
        ...
    }
}
----

That would require to define class inheritance rules on this annotation
as well as method inheritance.

If we go that way, we might even imagine more features down the road like
`@ValidateOnCall(OBJECT)` to validate the whole object upon specific
method calls.
That would make the JAX-RS integration more "standard" but would force
people to explicitly mark components that ought to be method constrained
which we agreed was not the best outcome:

* verboseness - constraints declared and metadata annotation used
* easy to forget

=== Against `@ValidateOnCall`

Gunnar is on the side of not introducing `@ValidateOnCall` as it can be simulated
by groups:

[source,java]
----
public static class Foo {

   //doesn't get validated during method validation of Default group
   @NotNull(groups=AllConstraints.class)
   private String getBar() { ... }

   //does get validated during method validation
   @NotNull
   private String getBaz() { ... }
}

//use this e.g. to validate upon entity persisting
public interface AllConstraints extends Default {}
----

My problem with this approach is its verboseness and the fact that
teams might want to preemptively use this verbose pattern "just in
case".
```

**Comment by DavideD** [comment]
> @DavideD can you take the first issues in order?

@emmanuelbernard OK

**Comment by xcoulon** [comment]
@emmanuelbernard thanks for your feedback ! 
As far as responsive top navbar is concerned, I think that it's missing some JS scripts. To simplify the maintenance, it would probably be interesting to be able to retrieve those scripts from the patternfly-sass gem: https://github.com/patternfly/patternfly-sass/tree/master/assets/javascripts, so that in the future, upgrading this gem would be enough to upgrade both CSS and JS.

**Comment by hferentschik** [comment]
Awesome

**Comment by xcoulon** [comment]
@emmanuelbernard aa agreed with @DavideD, I pushed another couple of commits to fix the duplicate titles on the .md files and to make the top nav bar responsive.

**Comment by xcoulon** [comment]
@emmanuelbernard I added your `test.adoc` file and the rendered HTML page actually includes the Disqus comments. Could you give it another try to verify that it works, please ?

**Comment by DavideD** [comment]
@xcoulon It seems the FontAwesome fonts are missing, I'm going to add them

**Comment by emmanuelbernard** [comment]
@xcoulon looks like it works indeed (disqus comments). That must be my eyes ;)

**Comment by xcoulon** [comment]
@emmanuelbernard ok, cool !
@DavideD right, I probably forgot the Font-Awesome declaration in the base layout

**Comment by DavideD** [comment]
Superseeded by: https://github.com/beanvalidation/beanvalidation.org/pull/24

**Comment by hferentschik** [comment]
i am seeing this error when trying to build `rake gen`:

    An error during rendering /stylesheets/ie.scss occurred.
    While processing file /Users/hardy/work/hibernate/git/beanvalidation/beanvalidation.org/stylesheets/ie.scss
    An error occurred: Error: File to import not found or unreadable: blueprint
           Parent style sheet: /Users/hardy/work/hibernate/git/beanvalidation/beanvalidation.org/stylesheets/ie.scss
            on line 1 of stylesheets/ie.scss
    >> @import "blueprint";

Anyone else?

**Comment by DavideD** [comment]
Yes, I have the same error.

I haven't tried rake gen before. I suposse a CSS is missing

**Comment by hferentschik** [comment]
gen is building the whole site, all pages are build upfront this case. This is usually what one do first. I am surprised that `preview` does not have a dependency to `gen`. Something is fishy with the `Rakefile` here.

**Comment by DavideD** [comment]
I think that file (ie.scss) can be removed. It seems related to the previous theme

**Comment by DavideD** [comment]
It seems to work after that

**Comment by DavideD** [comment]
I've added a commit to [my pull request](https://github.com/beanvalidation/beanvalidation.org/pull/24) that removes it

**Comment by gunnarmorling** [comment]
Can this one be closed, now that #24 is there?

**Pull request closed without merging**
